### ISSUE TITLE
Zollnar- Inactive status when the scraper is running

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/Scrapers-UI#109]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/zollner/index.html
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See the status of the scraper as inactive
EXPECTED RESULTS:
Status Activ
ACTUAL RESULTS:
Inactive status when the scraper is running

<img width="944" alt="Screenshot 2023-10-28 124714_scraper" src="https://github.com/peviitor-ro/Scrapers-UI/assets/118441061/ddc527af-1828-434b-8a66-a82349c06ee0">

**Comment by davidmondoc** [comment]
acum ruleaza
<img width="1663" alt="Screenshot 2023-11-12 at 1 06 56 PM" src="https://github.com/peviitor-ro/Scrapers-UI/assets/61200936/9484db73-5de9-4867-8348-844f81f3e270">
