### ISSUE TITLE
RSMRomania- 'Rsmromania Careers' button does not open the careers page of the company website

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapers-UI#117]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for RSMRomania Company
3. Click on [Rsmromania Careers]  button
![Screenshot_60](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/fc42f102-b5af-42b7-ad5a-8f1e76d2504e)

EXPECTED RESULTS:
[Rsmromania Careers] button opens the careers page of the company website

ACTUAL RESULTS:
[Rsmromania Careers] button does not open the careers page of the company website

**Comment by melania23m** [comment]
now, the functionality of the buttons are implemented.
