### ISSUE TITLE
SHEsoftware - Scraper UI page not found

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapers-UI#118]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/ and https://scrapers.peviitor.ro/
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)type SHEsoftware in the search bar
3)click on the SHEsoftware name

EXPECTED RESULTS:
page https://scrapers.peviitor.ro/src/SHEsoftware/index.html - opens
 

ACTUAL RESULTS:
an error is displayed
"Page Not Found"
 
![Screenshot_62](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/9aa4f3dc-163b-48cd-aba2-7ed111647fd9)

**Comment by lalalaurentiu** [comment]
Nu se poate Adaugă deoarece scraperul e făcut in Jmeter.

**Comment by lalalaurentiu** [comment]
Fixed!
