### ISSUE TITLE
INVALID Ninjaone Careers Link

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapers-UI#120]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/ninjaone/#
browser: Chrome/ Microsoft Edge

STEPS TO REPRODUCE:

1. open URL in the browser
2. click on the [Ninjaone Careers] 

EXPECTED RESULTS:
the careers page on the Ninjaone website opens

ACTUAL RESULTS:
the link for the careers page on the Ninjaone website does not open.
the link does not open, it remains on the current page.

**Comment by davidmondoc** [comment]
rezolvat. am pus si link catre targetare si catre careers

**Comment by LarisaM16** [comment]
Verific! Multumesc!
