### ISSUE TITLE
Logo missing at Edenred

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#163]
ENVIROMENT: production
COMPANY: Edenred
URL: [Edenred peviitor.ro](https://scrapers.peviitor.ro/src/edenred/)
Company's Career website: [Edenred official website](https://www.edenred.ro/ro/descopera-jobul-potrivit)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

Click on Firme from footer.
Enter Edenred in the search bar.
Click the button under the company's logo.

Expected result:

You can see the company's logo.

Actual result:

The company's logo is missing.
<img width="1176" alt="edenred1 2 2 2" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/5abec067-8e40-4144-8f0d-d5d7b35490aa">

**Comment by davidmondoc** [comment]
@AdelinaGuliman  logo este pe site. te rog retesteaza
