### ISSUE TITLE
Logo missing at Hitachienergy

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#164]
ENVIROMENT: production
COMPANY: Hitachienergy
URL: [Hitachienergy peviitor.ro](https://scrapers.peviitor.ro/src/hitachienergy/index.html)
Company's Career website: [Hitachienergy official website](https://www.hitachienergy.com/careers/open-jobs?filterable0-location=Romania%2FBucharest++Ilfov&filterable0-offset=0&filterable0-calculatedOffset=0)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

Click on Firme from footer.
Enter Hitachienergy in the search bar.
Click the button under the company's logo.

Expected result:

You can see the company's logo.

Actual result:

The company's logo is missing.
<img width="1236" alt="bug hitachienergy" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/47e9eddf-9c57-444e-b1af-4a4bd1b11308">

**Comment by davidmondoc** [comment]
am adaugat linkul logo-ului in cod
