### ISSUE TITLE
Eon - Missing graphic

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#165]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Eon" Company
3. Check the graphic

EXPECTED RESULTS:
The graphic is displayed and all data is updated

 ACTUAL RESULTS:
 Missing graphic

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/3dd0b181-4401-4eb2-927a-b9b9ce920e94)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/2f7f5687-11a4-4f73-bb58-51feaa24b50c)

**Comment by davidmondoc** [comment]
a fost o eroare pe site. s-a rezolvat
![Uploading Screenshot 2023-11-09 at 10.20.37 PM.png…]()
