### ISSUE TITLE
Lipsește diagrama la SugarCRM

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#168]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/sugarcrm/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
apare diagrama

ACTUAL RESULTS:
spațiul pentru diagramă nu este completat

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/a694aa19-c838-48d5-9bc5-bf8b7aaedebc)

**Comment by davidmondoc** [comment]
am moficat. astept aprobareaa modificarilor. te rog verifica maine sau luni
