### ISSUE TITLE
Eroare nume companie la SugarCRM

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#169]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/sugarcrm/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
nume companie SugarCRM

ACTUAL RESULTS:
apare nume companie SugarCrm_scraper

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/49d2897a-e61a-4910-8c09-70c331eedc1d)

**Comment by davidmondoc** [comment]
am moficat. astept aprobareaa modificarilor. te rog verifica maine sau luni
