### ISSUE TITLE
Lipsește diagrama la NEW ERA TEHNOLOGY

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#170]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/neweratechnology/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
apare diagrama

ACTUAL RESULTS:
spațiul pentru diagramă nu este completat

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/2343747f-1d40-4d3b-b88c-8eb0e879814f)

**Comment by davidmondoc** [comment]
am moficat. astept aprobareaa modificarilor. te rog verifica maine sau luni
