### ISSUE TITLE
Eroare nume companie la NEW ERA TEHNOLOGY

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#171]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/neweratechnology/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
nume companie NEW ERA TEHNOLOGY

ACTUAL RESULTS:
apare nume companie NewEraTechnology_scraper

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/d7d9b739-5ff9-42c7-ab89-c3e61e0fd5bc)

**Comment by davidmondoc** [comment]
am moficat. astept aprobareaa modificarilor. te rog verifica maine sau luni
