### ISSUE TITLE
Eroare nume companie la ONAPSIS ROMANIA

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#175]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/onapsis/index.html#
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
nume companie ONAPSIS ROMANIA

ACTUAL RESULTS:
apare nume companie Onapsis_scraper

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/2388d343-2c5e-4c4c-b3d4-1b0107c7a81b)

**Comment by davidmondoc** [comment]
am moficat. astept aprobareaa modificarilor. te rog verifica maine sau luni
