### ISSUE TITLE
Apare de 2 ori Onapsis Careers la logo

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#176]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/onapsis/index.html#
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
să apară "Onapsis Careers" si "Targetare.ro"

ACTUAL RESULTS:
Apare de 2 ori Onapsis Careers

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/3464f35a-de17-45e9-a287-a3019a914c57)

**Comment by davidmondoc** [comment]
rezolvat. te rog verifica maine
