### ISSUE TITLE
nu ruleaza scraperul

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#196]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/neweratechnology/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
merge scraperul

ACTUAL RESULTS:
apare eroarea "python3: can't open file 'NewEraTechnology_scraper.py'", "no data in local storage" si status inactiv

![image](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/296dd8a9-688d-46fd-932b-306607a4c494)

**Comment by davidmondoc** [comment]
La mine rulează. Te rog mai verifică odată și la tine

**Comment by Luizalien** [comment]
Da, azi rulează și la mine

dum., 12 nov. 2023, 12:13 David Mondoc ***@***.***> a scris:
