### ISSUE TITLE
Nu apare logo-ul la Plannet

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#200]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/plannet/index.html
Browser: Chrome
Device: Laptop 
OS: Windows

STEPS TO REPRODUCE:
Deschide URL in browser

EXPECTED RESULTS:
Ar trebui sa apara o logo-ul

ACTUAL RESULTS:
Lipseste logo-ul

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/179b79df-aad1-41f3-a92f-c67e330a0c1b)

**Comment by davidmondoc** [comment]
rezolvat. te rog verific din nou de mine
