### ISSUE TITLE
La firma Sofidel pe scraper sunt joburile de la firma Plannet

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#202]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/sofidel/index.html
Browser: Chrome
Device: Laptop 
OS: Windows

STEPS TO REPRODUCE:
Deschide URL in browser

EXPECTED RESULTS:
Ar trebui sa apara joburile disponibile de la firma Sofidel

ACTUAL RESULTS:
Apar joburile de la firma Plannet

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/4d6f6f4c-a5aa-4dd7-904a-24d219ce40fa)

**Comment by davidmondoc** [comment]
rezolvat. te rog verific din nou de maine
