### ISSUE TITLE
Ciklum - "targeting" link is missing

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapers-UI#206]
ENVIRONMENT: PROD
URL: https://scrapers.peviitor.ro/src/ciklum/
browser: Chrome

STEPS TO REPRODUCE:
1)open URL in the browser
2) go to the "Ciklum " logo and check link for "targeting"

EXPECTED RESULTS:
"targeting" link appear

ACTUAL RESULTS:
the link is missing
![Screenshot_12](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/639508dd-e514-4a6e-90cb-17f99406c09a)

**Comment by OvidiuAl3x** [comment]
Nu exista firma pe targetare
