### ISSUE TITLE
Overlaid images

### ISSUE THREAD

**Issue by brahutz** [peviitor-ro/Scrapers-UI#208]
ENVIRONMENT: production
URL: https://peviitor.ro/rezultate?q=takeandeat&country=Rom%C3%A2nia&page=1
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser
Go to "Responsabil-gestiune-grandchef" and click the "Vezi postul" 

EXPECTED RESULTS:
The images are displayed correctly

ACTUAL RESULTS:
The images are overlaid

![RESPONSABIL-GESTIUNE-GRANDCHEF-Take-Eat-livrari-la-domiciliu-Iasi-Take-Eat-–-livrari-la-domiciliu-Iasi](https://github.com/peviitor-ro/Scrapers-UI/assets/130207713/b2fc9c86-08cc-4c4d-8d64-6a301b490a9e)

**Comment by davidmondoc** [comment]
buna @RaresCode. bugul asta e pe situl lor la ecranele mici. pe 13.3 inch se vede suprapus. pe 21 inch se vede bine. butul asta ar trebui sa li-l raportezi direct lor. si iti recomand sa faci asa poate, si nu glumesc, prinzi ceva contract/job la ei sa le testezi situl.

daca nu il raportezi tu, pot sa il raportez eu. ;)

<img width="1440" alt="Screenshot 2023-11-13 at 4 01 35 PM" src="https://github.com/peviitor-ro/Scrapers-UI/assets/61200936/8e746cef-4f92-4023-b6f4-85c0ac1c93a6">
