### ISSUE TITLE
Kelloggs - Scraper is not working

### ISSUE THREAD

**Issue by AdrianSandu92** [peviitor-ro/Scrapers-UI#223]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL: [https://scrapers.peviitor.ro/src/kelloggs/index.html/](url)
2) Click: "Run scraper" button

EXPECTED RESULTS:
Scraper should be active and functional

ACTUAL RESULTS:
**Scraper status: INACTIVE -- and the page is displaying this error: _"python3: can't open file 'kelloggs.py': [Errno 2] No such file or directory"_**
![image (1)](https://github.com/peviitor-ro/Scrapers-UI/assets/122230734/473478da-b299-4d60-9144-1dbdb48ed5ef)

**Comment by OvidiuAl3x** [comment]
Nu mai exista firma
