### ISSUE TITLE
JacobsDouweEgberts - Graph without active data

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#225]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "JacobsDouweEgberts" Company
3. Chech the graph functionality

EXPECTED RESULTS:
The graph is active, it shows the number of valid jobs in the last few days

ACTUAL RESULTS:
Graph without active data

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/fede981f-6942-4e4b-9417-f6ff7a0e5844)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the graph is active and display correct data


![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/58762120-752b-43d1-964e-01cde3e87108)
