### ISSUE TITLE
Kellanova - The "Career" and "GitHubRepo" buttons do not work or do not give valid answers; The company name on scrapers.peviitor.ro is "Kellanova_scraper"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#226]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Kellanova" Company
3. Check the functionality of the "Career" and "GitHubRepo" Buttons
4. Check the company name 

EXPECTED RESULTS:
The "Career" button opens the career section on the company's website
The "GitHubRepo" button opens the "Scrapers_Cristi_Olteanu" repository
The company name on scrapers.peviitor.ro is "Kellanova"

ACTUAL RESULTS:
The "Career" and "GitHubRepo" buttons do not work or do not give valid answers
The company name on scrapers.peviitor.ro is "Kellanova_scraper"

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/122023703/bbd98695-e71e-415f-9c1e-5473dc2b57a2)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/122023703/0f5242df-1194-44d4-944d-29f8299c7b25)

**Comment by AdrianaCionca** [comment]
After retesting, the company name on scrapers.peviitor.ro is "Kellanova_scraper"

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/f2d07cb6-a14a-4a59-bbb6-69657e2461fd)

**Comment by OvidiuAl3x** [comment]
> After retesting, the company name on scrapers.peviitor.ro is "Kellanova_scraper"
> 
> ![image](https://user-images.githubusercontent.com/122023703/283494876-f2d07cb6-a14a-4a59-bbb6-69657e2461fd.png)

Numele e afisat automat dupa numele fisierului din repo.
