### ISSUE TITLE
Expressvpn - Scraper-UI Error 404 

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#231]
ENVIROMENT: production
COMPANY: Expressvpn
URL: [Expressvpn peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Expressvpn in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"
<img width="1231" alt="Screenshot at Nov 14 14-23-23" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/05d9c2ed-f39d-4953-a0c4-295bda1fb1cb">

**Comment by davidmondoc** [comment]
@AdelinaGuliman rezolvat. te rog retesteaza
