### ISSUE TITLE
Vodafone - Different number of jobs on scrappers.peviitor.ro then on Vodafone Careers

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#236]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/vodafone/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open the URL in browser
2) Click on 'Run Scraper' button
3) Check section 'Jobs'
4) Go to Vodafone logo
5) Click on Careers
6) Check jobs on Vodafone Careers

EXPECTED RESULTS:
The number of jobs on https://scrapers.peviitor.ro/src/vodafone/index.html is the same as the number of jobs on Vodafone Careers

ACTUAL RESULTS:
The number of jobs on https://scrapers.peviitor.ro/src/vodafone/index.html (198) is different then on Vodafone Careers (192)
![cap04](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/cf5e92a6-953f-400f-8d4b-1e9b56803a2d)

![cap05](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/c49fec3a-1e3d-4d85-8a1b-34d77ec9137a)

**Comment by lalalaurentiu** [comment]
The scraper also extracts some jobs from outside the country, but the number of jobs on peviitor is correct.

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/158ff08a-fc29-489b-877b-1bbfaef1ea62)

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/590cdbdd-8fca-43e6-9958-d25d4faea1c2)
