### ISSUE TITLE
Phinia- missing "targetare" link

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/Scrapers-UI#244]
ENVIRONMENT: PROD
url: https://scrapers.peviitor.ro/src/phinia/index.html
browser: Chrome

STEPS TO REPRODUCE:
1)open url in the browser
2)check "targetare" link
 
EXPECTED RESULTS:
the link should   be functional
![Screenshot_3](https://github.com/peviitor-ro/Scrapers-UI/assets/124587607/7b10487c-2b01-4fc8-a35b-fe1922619ef2)

ACTUAL RESULTS:

Targetare link is not displayed

**Comment by davidmondoc** [comment]
@LarisaM16 rezolvat. te rog verifica maine
