### ISSUE TITLE
MegaImage-missing displaying the number of jobs on the graph

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#245]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "MegaImage" Company https://scrapers.peviitor.ro/src/megaimage/
3.Check the number of jobs on the graph

EXPECTED RESULTS:
The number of jobs should be displayed on the graph

ACTUAL RESULTS:
The scraper does not displayed jobs numer for de company

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/bb007df2-da86-4e9a-9fb3-c9cb09c9e424)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting**
Run scraper and refresh
The bug is no longer reproducible with the initial steps.
Data is now correct after fixing the bug.
Validating the bug fix
