### ISSUE TITLE
S&P - Scraper-UI Error 404

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#251]
ENVIROMENT: production
COMPANY: S&P
URL: [S&P peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter S&P in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"
<img width="1081" alt="Screenshot at Nov 16 15-44-54" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/ec393059-1ac8-4348-872f-d74bc134d7bd">

**Comment by davidmondoc** [comment]
@AdelinaGuliman te rog sa imi spui la ce scraper e compania ca nu o gasesc

**Comment by AdelinaGuliman** [comment]
<img width="969" alt="Screenshot at Nov 17 12-59-23" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/753d5a0b-6da4-40c0-bf3c-ca2211f3451f">
