### ISSUE TITLE
BRD - Status "Inactive"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#256]
ENVIRONMENT: production
URL: https://scarpers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "BRD" Company and Run scraper 
3. Check the "Status" 

EXPECTED RESULTS:
The status is "Active"

ACTUAL RESULTS:
The Status is "Inactive"

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/817aa0e8-9d74-4565-bbe0-c2d8ed4ec585)

**Comment by AdiVanca** [comment]
After testing in scrapers UI the status for BRD is Inactive again

![a9](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/aabaa7f9-38c7-43d1-b707-19e54dfd18f0)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the status is active.
