### ISSUE TITLE
CNI - Graph does not present the active jobs

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#259]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Write CNI company
3. Run scraper
4. Check the graph 

EXPECTED RESULT:
All valid jobs can be observed on the graphic.

ACTUAL RESULT:
The graph does not present the data.

![Screenshot_19](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/a4f0d7da-e90e-4836-96ed-367e286ee856)

**Comment by lalalaurentiu** [comment]
Fixed!
<img width="1440" alt="Screenshot 2023-11-17 at 23 33 51" src="https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/a6733c11-ddfd-4d71-9850-9455cd06e4be">

**Comment by RafayBeatrice** [comment]
Works!
