### ISSUE TITLE
Apanova - Status "Database"

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#260]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type the name of the company in the search bar
3. Run scraper
4. Check the status

EXPECTED RESULT:
Status to be "Active"

ACTUAL RESULT:
Status is "Database"

![Screenshot_23](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/67be2309-2d54-4697-af45-f68cd8bd9225)

**Comment by lalalaurentiu** [comment]
apnoea s-a schimbat în apanovabucuresti

**Comment by RafayBeatrice** [comment]
It work!
