### ISSUE TITLE
Apanova - Logo is missing

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#261]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type the name of the company in the search bar

EXPECTED RESULT:
We can see the logo.

ACTUAL RESULT:
The logo is missing.

![Screenshot_21](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/10f9b7c0-f8d3-46a9-878b-4a96794b153e)

**Comment by lalalaurentiu** [comment]
apnoea s-a schimbat în apanovabucuresti

**Comment by RafayBeatrice** [comment]
It work!
