### ISSUE TITLE
Maviprod - Status "Database"

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#262]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type the name of the company in the search bar
3. Run scraper
4. Check the status

EXPECTED RESULT:
Status to be "Active"

ACTUAL RESULT:
The status is "Database"

![Screenshot_24](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/2fef7f9f-d1e3-4fc1-9200-d7296665cec5)

**Comment by lalalaurentiu** [comment]
Fixed!
<img width="1440" alt="Screenshot 2023-11-17 at 23 52 51" src="https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/96719dea-5c18-43dd-b040-8713b262b491">

**Comment by RafayBeatrice** [comment]
It work!
