### ISSUE TITLE
Cabuzau - Status "Database"

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#263]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type the name of the company in the search bar
3. Run scraper
4. Check the status

EXPECTED RESULT:
Status to be "Active"

ACTUAL RESULT:
Status is "Database"

![Screenshot_25](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/c742ae49-8369-4c8c-9b5a-7aece0e6ee0c)

**Comment by lalalaurentiu** [comment]
cabuzau s-a schimbat în compania de apa Buzău

**Comment by RafayBeatrice** [comment]
It work!
