### ISSUE TITLE
Cabuzau - Logo is missing

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#264]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type the name of the company in the search bar

EXPECTED RESULT:
We can see the logo.

ACTUAL RESULT:
The logo is missing.

![Screenshot_26](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/6da36b18-9541-45c2-8b10-684faa1de83c)

**Comment by lalalaurentiu** [comment]
cabuzau s-a schimbat în compania de apa Buzău.

**Comment by RafayBeatrice** [comment]
It work!
