### ISSUE TITLE
Apanovabucuresti - No job type

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#268]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type the name of the company in the search bar
3. Check field jobs

ACTUAL RESULT:
See "full-time" on-field job.

EXPECTED RESULT:
In the description of jobs on the website, they say the program for work and the location. But the job type can't be seen in our field.
![Screenshot_7](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/5f150266-34b2-412f-85d3-03713f34250d)
![Screenshot_8](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/56055940-d931-4d0e-885c-1b144e3c5bed)

![Screenshot_4](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/21b76e7e-5a24-4611-8182-ec240d5bb482)

**Comment by OvidiuAl3x** [comment]
No job type se refera daca jobul e remote si daca nu e apare acel No job type
