### ISSUE TITLE
Lseg - Status "Inactive"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#274]
ENVIRONMENT: production
URL: https://scarpers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Lseg" Company and Run scraper 
3. Check the "Status" 

EXPECTED RESULTS:
The status is "Active"

ACTUAL RESULTS:
The Status is "Inactive"

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/28edcb0b-b11e-42b2-9d3a-5bae379fbca2)

**Comment by AdrianaCionca** [comment]
After retesting, the Status is "Active"
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/a944ec42-c190-4760-8e3b-5c1eb53ab90c)

**Comment by AdiVanca** [comment]
The bug reproduce again
![a38](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/47bc9f3f-e447-4042-8365-101645fa1ccc)

**Comment by AdrianaCionca** [comment]
After retesting, the Status is "Active"
