### ISSUE TITLE
Solo - The "Career" button does not work or does not provide valid answers

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#275]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Solo" Company
3. Check the functionality of the "Career" Button

EXPECTED RESULTS:
The "Career" button opens the career section on the company's website

ACTUAL RESULTS:
 The "Career" button does not work or does not give valid answers

https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/77babf1d-21d4-4eaa-92d3-d13e413842d4

**Comment by AdrianaCionca** [comment]
After retesting, the "Career" button still doesn't work or doesn't give valid answers

**Comment by OvidiuAl3x** [comment]
Modificarile au fost adaugate, te rog sa  retestezi

**Comment by AdrianaCionca** [comment]
After retesting, the "Career" button opens the career section on the company's website
