### ISSUE TITLE
Tickbird - The message "No City" is displayed at the job location; The job is remote

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#277]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Tickbird" Company
3. Check the job location

EXPECTED RESULTS:
No message is displayed at the job location because the job is remote

ACTUAL RESULTS:
The message "No City" is displayed, the job is remote

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/45f51e4c-cc5f-4fa2-92cc-b232a7252656)

**Comment by OvidiuAl3x** [comment]
Nu apare city ca e remote jobul, apare mai jos remote sub Romania

**Comment by lalalaurentiu** [comment]
> Nu apare city ca e remote jobul, apare mai jos remote sub Romania

Este bug pe ui deoarece ui-ul trebuia sa nu mai scrie "no City" in câmpul location. A fost gandit când găsește "Remote" sa afișeze totul cu verde

**Comment by AdrianaCionca** [comment]
After retesting, the message "No City" is still displayed, the job is remote


![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/3b09c78b-b096-47dd-85d5-a2b3e257807b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the location is displayed correctly
