### ISSUE TITLE
IntesaSanpaoloBank - Graph without active data for the jobs on https://scrapers.peviitor.ro/

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#278]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper and search " IntesaSanpaoloBank" Company 
3. Chech the graph functionality

EXPECTED RESULTS:
The graph must have activ data and show the number of valid jobs

ACTUAL RESULTS:
Graph without active data, doesn't show the number of valid jobs

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/ff87ebe8-9ac7-4cb9-9324-29ff2938f869)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting**
Run scraper and refresh
The bug is no longer reproducible with the initial steps.
Data is now correct after fixing the bug.
Validating the bug fix
