### ISSUE TITLE
FORTECH - All the jobs have "remote" status on https://scrapers.peviitor.ro/

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#279]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "FORTECH" Company
3. Check the "Job Type"

EXPECTED RESULTS:
All the jobs of this company are located in Cluj Napoca

ACTUAL RESULTS:
The "remote" message is displayed and not necesary
On the https://solr.peviitor.ro/solr the message "remote" is displayed.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/5ac1a531-45c6-4227-9143-7c8742800179)

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/a9c27740-f582-420d-a5cb-14b4949c6ba3)

**Comment by lalalaurentiu** [comment]
Why not? All jobs are Remote, Hybrid and On-Site
