### ISSUE TITLE
grubhub - Scraper-UI Error 404

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#280]
ENVIROMENT: production
COMPANY: grubhub
URL: [grubhub peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter grubhub in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"
<img width="975" alt="Screenshot at Nov 21 15-05-06" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/7af5a8dd-34c6-4819-8228-b4817beb6bd8">
<img width="1116" alt="Screenshot at Nov 21 15-05-21" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/ebe7931d-f3a4-48a7-aabe-427228ec86f5">

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x sorry but it's not Fixed

**Comment by OvidiuAl3x** [comment]
Modificarile au fost audagate, te rog sa  retestezi
