### ISSUE TITLE
hartrodt - Scraper-UI Error 404

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#281]
ENVIROMENT: production
COMPANY: hartrodt
URL: [hartrodt peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter hartrodt in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"
<img width="894" alt="Screenshot at Nov 21 15-11-29" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/0ea1d002-0579-41b3-a6f6-8af92327ed12">
<img width="1066" alt="Screenshot at Nov 21 15-11-42" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/d7fc341d-082c-44e0-bf93-fc8cb6b0967c">

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x sorry but it's not Fixed

**Comment by AdelinaGuliman** [comment]
ok. o sa restestez maine

**Comment by OvidiuAl3x** [comment]
Modificarile au fost audagate, te rog sa  retestezi
