### ISSUE TITLE
Onapsis - The "GitHubRepo" button doesn't work or doesn't give valid answers

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#283]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/onapsis/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser

Run scraper for "Onapsis" Company

Check the functionality of the "GitHubRepo" Button

EXPECTED RESULTS:
The "GitHubRepo" button opens the "Scrapers_canghelet" repository

ACTUAL RESULTS:
The "GitHubRepo" button doesn't work or doesn't give valid answers

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/1848dfdf-0f09-42b9-a716-8d170bea6be8)

**Comment by lalalaurentiu** [comment]
fixed!
