### ISSUE TITLE
Tain - The "GitHubRepo" button doesn't work or doesn't give valid answers

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers-UI#292]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/tain/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser

Run scraper for "Tain" Company

Check the functionality of the "GitHubRepo" Button

EXPECTED RESULTS:
The "GitHubRepo" button opens the "Scrapers_canghelet" repository

ACTUAL RESULTS:
The "GitHubRepo" button doesn't work or doesn't give valid answers

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/08042276-4a51-49a3-bb1f-bf355bdb551f)

**Comment by lalalaurentiu** [comment]
Fixed!
