### ISSUE TITLE
"Careers" and "Targetare" links are switched

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#295]
ENVIROMENT: production
COMPANY: Cmed
URL: [Cmed peviitor.ro](https://scrapers.peviitor.ro/src/cmed/)
Company's Career website: [Cmed official website](https://aixialgroup.hire.trakstar.com/#content')
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/cmed/) must be open in browser.

Steps:
1. Hover over the company logo.
2. Click Careers text.

Clicking the Careers text should open a new window to [Cmed](https://aixialgroup.hire.trakstar.com/#content') official website.

Actual result:
Careers opens a new window to [Cmed](https://targetare.ro/22643945/aixial-cro-srl). The links are reversed.
<img width="722" alt="Screenshot 2023-11-22 at 20 14 32" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/552777f8-58d7-4c9a-90c8-b9d457e9a0a0">

<img width="723" alt="Screenshot 2023-11-22 at 20 14 47" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/36b0d6bc-1b49-4071-9018-8474d3194d93">

**Comment by davidmondoc** [comment]
@iBixee buna. am rezolvat bugul. te rog verifica maine dupa actualizarea bazei de date.

**Comment by iBixee** [comment]
> @iBixee buna. am rezolvat bugul. te rog verifica maine dupa actualizarea bazei de date.

Multumesc, David! Will do!
