### ISSUE TITLE
Oracle - The company logo is different on scrapers.peviitor.ro from the company logo on their website.

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#298]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/oracle/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Check company logo
3) Mouse hover the company logo
4) Click on Careers
5) Check company logo on the company website

EXPECTED RESULTS:
The company logo is the same on both scrapers.peviitor.ro and the company website.

ACTUAL RESULTS:
The company logo is different on scrapers.peviitor.ro from the company logo on their website.

![cap025](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/caa0742d-7858-44eb-8429-36ae5ffbc695)
![cap026](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/ba7370c2-a53b-4658-bc4b-9abc0d43d492)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After Re-Test the company logo is displayed correctly
