### ISSUE TITLE
Danieli - Missing "Careers" and "Targetare" links

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#305]
ENVIROMENT: production
COMPANY: Danieli
URL: [Danieli peviitor.ro](https://scrapers.peviitor.ro/src/danieli/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/danieli/index.html) must be open in browser.

Steps:

1. Hover over the company logo.
2. Click Careers button.
3. Click Targetare button.

Expected result:
Clicking the Careers text should open a new window to the company's official career website.

Actual result:
The links fail to redirect to the intended website as expected.

<img width="752" alt="Screenshot 2023-11-23 at 19 27 46" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/791898cd-526e-47d5-ba90-587e6368c77b">

<img width="752" alt="Screenshot 2023-11-23 at 19 27 56" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/a8416637-4925-4b7b-936b-dda80da225e6">

**Comment by DianaDascalu2** [comment]
Updated careers link. Please check if it is correct now.

**Comment by iBixee** [comment]
The issue persists. Also, can't find it in the search section on (https://scrapers.peviitor.ro/).

<img width="826" alt="Screenshot 2023-11-23 at 21 23 29" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/466c2d37-7f6b-499c-8df6-00a68b6235bc">

<img width="828" alt="Screenshot 2023-11-23 at 21 23 09" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/d250e64b-72d2-43e5-9fdb-470b992c62e5">

<img width="838" alt="Screenshot 2023-11-23 at 21 23 44" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/d7385406-205b-4219-952d-463152bc8d93">

**Comment by iBixee** [comment]
Looks good now! Thanks! 👍
