### ISSUE TITLE
ExpressVPN - Missing "Careers" and "Targetare" links

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#312]
ENVIROMENT: production
COMPANY: ExpressVPN
URL: [ExpressVPN peviitor.ro](https://scrapers.peviitor.ro/src/expressvpn/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/expressvpn/index.html) must be open in browser.

Steps:

1. Hover over the company logo.
2. Click Careers button.
3. Click Targetare button.

Expected result:
Clicking the Careers text should open a new window to the company's official career website.
Clicking the Targetare text should open a new window to the company's Targetare webpage.

Actual result:
The links fail to redirect to the intended websites as expected.

<img width="767" alt="Screenshot 2023-11-24 at 14 42 13" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/de629f05-fd12-41a9-8001-662dc46d75c9">

<img width="768" alt="Screenshot 2023-11-24 at 14 42 27" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/ed9fa54c-8f2c-4bd2-bd58-1e92a315c034">

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
