### ISSUE TITLE
Tcandc - "Targetare.ro" button is not functional.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#335]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Tcandc" Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:
The "targetare.ro" button is functional and the page is opend.

ACTUAL RESULTS:
 "Targetare.ro" button is not functional.

https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/89f37ccd-d20c-4ba8-acb1-e0be13245784

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
