### ISSUE TITLE
Page not found at Onapsis GitHub repo page error

### ISSUE THREAD

**Issue by DianaDascalu2** [peviitor-ro/Scrapers-UI#336]
ENVIROMENT: production
COMPANY: Mindera
URL: https://github.com/peviitor-ro/Scrapers_canghelet/blob/main/sites/onapsis_scraper.py
Browser: Google Chrome
Device: laptop
OS: Windows 10

Precondition:
The https://github.com/peviitor-ro/Scrapers_canghelet/blob/main/sites/onapsis_scraper.py must be open in browser.

Steps:

Click on Github Repo.
Page goes to page not found message.

Expected result:
Click the GitHub repo.
Hogarth's scraper GitHub page should open un.

Actual result:
The button takes us to Page not found message.
![Screenshot 2023-11-28 183115](https://github.com/peviitor-ro/Scrapers-UI/assets/118655267/ae888dab-92b4-4f60-af1a-254b24b4912a)

**Comment by lalalaurentiu** [comment]
Fixed!
