### ISSUE TITLE
Panifcom - Missing "Targetare.ro" button.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#338]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Panifcom " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:
The "targetare.ro" button is functional and the page is opend.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/91508bed-14c8-4325-9f33-82277c40fbe5)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested,  The "Targetare.ro" button is functional and the page is opend.
