### ISSUE TITLE
PPT - The Scrapers UI does not recognize "Campulung Muscel" as a city

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#340]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "PPT" Company
3. Check the location for the job: "Coordonator transporturi " 

EXPECTED RESULTS:
The location for the job "Coordonator transporturi " is "Campulung Muscel"

ACTUAL RESULTS:
The scraper does not recognize "Campulung Muscel" as a city
The message "Campulung Muscel is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/ed0d6d9d-9f8c-4f13-aafb-8ccb50a8882d)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/16c32da6-de6a-4a67-a151-134d31b4c1cb)
