### ISSUE TITLE
Nokia - Missing "Targetare.ro" button.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#341]
NVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Nokia " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:
The "targetare.ro" button is functional and the page is opend.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/99a0bf6c-9645-42a3-b29f-69ea95fe92f6)

**Comment by davidmondoc** [comment]
@Geo843 sunt 2 companii nokia. pe care din ele e deschis bugul? - ar trebui mai inainte sa tergem una din ele @lalalaurentiu

**Comment by Geo843** [comment]
@davidmondoc , am facut pentru compania asta: https://careers.nokia.com/jobs/search/40601155
Am si deschis un bug report legat de logo dublat astazi.

**Comment by Geo843** [comment]
After retesting, "Targetare.ro"  button appear and it is functional.
