### ISSUE TITLE
Romstal - The scraper UI doesn't recognize "Cluj Napoca" as a city ("CLUJ - NAPOCA is not a city in Romania")

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#344]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Romstal" Company
3. Check the location for the jobs: "Lucrator Comercial Cluj " and "Consilier Vanzari Showroom Cluj Napoca"

EXPECTED RESULTS:
The location for the jobs "Lucrator Comercial Cluj " and "Consilier Vanzari Showroom Cluj Napoca" is Cluj Napoca

ACTUAL RESULTS:

- On scrapers.peviitor.ro the message "CLUJ - NAPOCA is not a city in Romania" is displayed 
- The scraper UI doesn't recognize "Cluj Napoca" as a city

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/8b8e0aa9-1f00-4537-b264-d86c29c963d6)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/4460bbbb-b983-434b-8095-267b20df642f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting**
Run scraper and refresh

1. Data is now correct after fixing the bug for this job: "Lucrator Comercial Cluj "
2. The scraper has not returned data for this job:  "Consilier Vanzari Showroom Cluj Napoca". 
    Job is still displayed on the company's website



![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/efb53e24-e478-4d22-8fe3-8e6f9ccee188)
