### ISSUE TITLE
Nagarro - Missing "Targetare.ro" button ; - Graph without active data for the jobs on; - "Vezi Postul" is red instead of green (Staff Engineer, PHP)

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#354]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Nagarro" Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"
5. Check the graph functionality .
6. Check the functionality and color of " Vezi Postul " at (Staff Engineer, PHP) position.

EXPECTED RESULTS:
1. The "targetare.ro" button is functional and the page is opend.
2. The graph must have activ data and show the number of valid jobs.
3. The color of "Vezi Postul " is green.

ACTUAL RESULTS:
1. Missing "Targetare.ro" button ; - Graph without active data for the jobs on.
2. "Vezi Postul" is red instead of green (Staff Engineer, PHP).

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/006d081c-5564-48cb-b9ac-d23a73a14945)

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/abf52acb-e06c-441e-88db-82a9970e88d9)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested,  The "targetare.ro" button is functional and the page is opened.
The graph must have active data and show the number of valid jobs.
The color of "Vezi Postul " is green.
