### ISSUE TITLE
ElectronicArts - Graph without active data; The GitHub Repo button returns a 404 error message

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#358]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "ElectronicArts" Company and run scraper
3. Check the graph functionality
4. Check the functionality of the "GitHub Repo" button.

EXPECTED RESULTS:
The graph is active, it shows the number of valid jobs in the last few days
The "GitHub Repo" button go to https://github.com/peviitor-ro/based_scraper_py

ACTUAL RESULTS:
 Graph without active data;
 The GitHub Repo button returns a 404 error message.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/fb028b0b-5602-4299-bd50-8794046cde85)

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/413144b6-3d01-4c10-9a63-d574f1e2f186)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the graph is active and it shows the number of valid jobs
The "GitHub Repo" button go to https://github.com/peviitor-ro/based_scraper_py/blob/main/sites/electronicarts.py

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/34e88256-d0a9-4639-b121-6e7c6e1688b4)


![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/3e46c4fe-e2b0-4c7b-a0f9-eb1dcbca2f0c)
