### ISSUE TITLE
Kaizengaming - Graph without active data for the jobs on ;  -Missing "Targetare.ro" button.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#364]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the "Kaizengaming " Company.
3. Click on the "Targetare.ro" button.
4. Check the graph functionality.

EXPECTED RESULTS:
1. The "Targetare.ro" button is functional and the page is opend.
2.The graph must have activ data and show the number of valid jobs.

ACTUAL RESULTS:
1. Graph without active data for the jobs on.
2.  Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/91a41532-9da8-4004-8aed-343d5b424ef3)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro and graph is working

**Comment by Geo843** [comment]
Re-tested, graph is working.
