### ISSUE TITLE
InterbrandsOrbico - Missing "Targetare.ro" button ; - Graph without active data for the jobs on

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#366]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "InterbrandsOrbico " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"
5. Check the graph functionality.

EXPECTED RESULTS:
1. The "Targetare.ro" button is functional and the page is opend.
2. The graph must have activ data and show the number of valid jobs

ACTUAL RESULTS:
 1. Missing "Targetare.ro" button 
 2. Graph without active data for the jobs on.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/28b50124-f26e-4a45-abdd-31bceeeb3e49)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested,  
The "Targetare.ro" button is functional and the page is opened.
The graph must have active data and show the number of valid jobs
