### ISSUE TITLE
Htecgroup - Missing "Targetare.ro" button.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#373]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Htecgroup " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro".

EXPECTED RESULTS:
The "Targetare.ro" button is functional and the page is opend.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/9aa6fa11-7367-4630-9090-437406b91681)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
