### ISSUE TITLE
Humanrise - Failed to load resource after pressing "See jobs" button

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#375]
ENVIROMENT: production
COMPANY: Humanrise
URL: [Humanrise Scraper-UI](https://scrapers.peviitor.ro/src/humanrise/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Humanrise in the search bar.
3. Click the button under the company's logo.
4. Click the Run Scraper button.
5. Click the See jobs button.

Expected result:
The list of available jobs listed on [www.peviitor.ro](https://peviitor.ro/rezultate?q=humanrise&country=Rom%C3%A2nia&page=1) opens

Actual result:
Failed to load resource: the server responded with a status of 404 
<img width="169" alt="Screenshot at Dec 06 13-25-26" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/e5e67ea2-4cf9-47a8-8b09-14087df62c4e">
<img width="1653" alt="Screenshot at Dec 06 13-22-59" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/a60c9e56-bcf7-4d2c-9da6-129623de72d2">

**Comment by lalalaurentiu** [comment]
retest, because its working

**Comment by AdelinaGuliman** [comment]
It works only if I press refresh

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/cb13ecbb-7f98-4822-90e3-c729e26f904c
