### ISSUE TITLE
Infosys - Failed to load resource after pressing "See jobs" button

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#376]
ENVIROMENT: production
COMPANY: Infosys
URL: [Infosys Scraper-UI](https://scrapers.peviitor.ro/src/infosys/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Infosys in the search bar.
3. Click the button under the company's logo.
4. Click the Run Scraper button.
5. Click the See jobs button.

Expected result:
The list of available jobs listed on [www.peviitor.ro](https://peviitor.ro/rezultate?q=infosys&country=Rom%C3%A2nia&page=1) opens

Actual result:
Failed to load resource: the server responded with a status of 404
<img width="169" alt="Screenshot at Dec 06 13-25-26" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/6353ec57-1472-4f21-bb9b-9422c17e1105">
<img width="1607" alt="Screenshot at Dec 06 14-08-35" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/9e0bf10c-ca13-4fb3-a96d-0deeb732f303">

**Comment by lalalaurentiu** [comment]
retest, because its working 

https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/44019fac-59df-43b6-8637-ae7b968de688
