### ISSUE TITLE
Vodafone-  Scraper does not recognize Targu Mures as a city in Romania

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#383]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/vodafone/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check location for 'Key Account Manager, MLE - Brasov- Mures' job

EXPECTED RESULTS:
Targu Mures is recognized as a city in Romania for 'Key Account Manager, MLE - Brasov- Mures' job

ACTUAL RESULTS:
The Scraper does not recognize Targu Mures as a city in Romania and displays 'Targu Mures is not a city in Romania'

![Cap027](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/e35015df-1361-44cc-bb92-641c6c23d4d4)

**Comment by lalalaurentiu** [comment]
job is no longer available
