### ISSUE TITLE
Segula - Status inactive

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#385]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/segula/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check Status section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The 'Inactive' message is displayed in the 'Status' section

![cap032](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/df601fa8-bdad-45a6-9ced-565c2ce6f2dc)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retest the ‘Activ’ message is displayed in ‘Status’ section
