### ISSUE TITLE
Qiagen - Targetare.ro does not open

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#390]
ENVIROMENT: production
COMPANY: Qiagen
URL: [Qiagen Scraper-UI](https://scrapers.peviitor.ro/src/infosys/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Qiagen in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo
5. Click on Targetare.ro button.

Expected result:
A new tab opens with the "Targetare.ro" page

Actual result:
The page intended for "Targetare.ro" does not open

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/344001b6-1561-406d-b4d0-01561a305379

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
