### ISSUE TITLE
Rws - The "Targetare.ro" button is missing

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#393]
ENVIROMENT: production
COMPANY: Rws
URL: [Rws Scraper-UI](https://scrapers.peviitor.ro/src/rws/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Rws in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo.

Expected result:
The "Creers" button and the "Targetare.ro" button appear

Actual result:
The "Targetare.ro" button is missing.

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/9bbe2fff-3fb0-4e9a-9630-34adb8259419

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
