### ISSUE TITLE
Ensemblesoftware - Missing " Targetare .ro" button

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#396]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "InterbrandsOrbico " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:

The "Targetare.ro" button is functional and the page is opened.

ACTUAL RESULTS:

Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/af5982e9-3331-42ea-9686-2ea3d92a00c6)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" button is functional and the page is opened.
