### ISSUE TITLE
Dualit - Missing " Targetare .ro" button

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#402]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Dualit " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:
The "Targetare.ro" button is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/1014e4fd-d205-4e66-bb87-f29af23adfe0)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" button is functional and the page is opened.
