### ISSUE TITLE
Sennder - Database Error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#405]
ENVIROMENT: production
COMPANY: Sennder
URL: [Sennder peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Sennder in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
The the company's database is updated.

Actual result:
TypeError: Failed to fetch.

<img width="1083" alt="Screenshot at Dec 07 17-42-23" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/8defac96-5eaa-4484-8ecc-b116ea9c5804">

**Comment by lalalaurentiu** [comment]
Working!

https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/3121e5c8-1dcc-4e45-bdde-6163f071e938
