### ISSUE TITLE
Cognizantsoftvision - Status "Inactiv"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#406]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Cognizantsoftvision" Company
3. Run scraper
4. Check the "Status" section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/263bbe4b-02ba-43f6-8f14-27c5257b77b5)

**Comment by lalalaurentiu** [comment]
It seems that there are no problems

https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/a69714f0-0b61-4ef0-9c2e-cba85e8d18d2

**Comment by AdrianaCionca** [comment]
After retesting, the Status is "Active"
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/b99abb4e-04b0-4b33-a2d9-830c98733dbd)
