### ISSUE TITLE
FlTechincs - The company's logo is missing

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#425]
ENVIROMENT: production
COMPANY: FlTechincs
URL: [FlTechincs scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/fltechincs/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter FlTechincs in the search bar.
3. Click the button under the company's logo.
4. The company-specific scraper page opens.

Expected result:
The company logo appears in the body of the page.

Actual result:
The company logo does not appears in the body of the page.
<img width="649" alt="Screenshot at Dec 08 15-28-20" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/925aa421-30f7-472f-9e05-4cbae0c028a3">

**Comment by lalalaurentiu** [comment]
scraper has been deleted
