### ISSUE TITLE
FlTechincs - The graphic design is wrong

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#426]
ENVIROMENT: production
COMPANY: FlTechincs
URL: [FlTechincs scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/fltechincs/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter FlTechincs in the search bar.
3. Click the button under the company's logo.
4. The company-specific scraper page opens.

Expected result:
The graphic appears in the body of the page

Actual result:
The graphic design is wrong.
<img width="1506" alt="Screenshot at Dec 08 15-44-06" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/84065118-8019-4fa3-8251-f5065ca5a49c">

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
