### ISSUE TITLE
FlTechincs - The "Careers" button doesn't work.

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#427]
ENVIROMENT: production
COMPANY: FlTechincs
URL: [FlTechincs scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/fltechincs/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter FlTechincs in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo
5. Click on "Careers".

Expected result:
The official page of the company opens.

Actual result:
The "Careers" button doesn't work.

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/db7576c5-d3de-4aa9-8ab8-aa50b0191b4e

**Comment by lalalaurentiu** [comment]
scraper has been deleted

**Comment by AdelinaGuliman** [comment]
@cristiol this scraper exists in your repository but @lalalaurentiu can't find it to fix it

**Comment by lalalaurentiu** [comment]
Fixed
