### ISSUE TITLE
FlTechincs - The GitHubRepo button returns a 404 error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#428]
ENVIROMENT: production
COMPANY: FlTechincs
URL: [FlTechincs scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/fltechincs/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter FlTechincs in the search bar.
3. Click the button under the company's logo.
4. Click on the 'GitHubRepo" button

Expected result:
The GitHubRepo button directs you to [Cristi Olteanu GitHubRepo](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/blob/main/sites/fltechincs.py)

Actual result:
The GitHubRepo button returns a 404 error.

<img width="1278" alt="Screenshot at Dec 08 16-17-45" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/eccea9aa-5c70-4def-871b-6de3e57613d5">

**Comment by lalalaurentiu** [comment]
scraper has been deleted
