### ISSUE TITLE
continentalhotels - UI BUG - The graphic of the job's number remains in small size after rescaling the screen 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers-UI#429]
ENVIROMENT: production
COMPANY: continentalhotels
URL: ](https://scrapers.peviitor.ro/src/continentalhotels/)
Browser: Chrome
Device: laptop
OS: Windows 10

Precondition:
The site (https://firme.peviitor.ro/) must be open in Chrome browser.

Steps:

Open the URL https://firme.peviitor.ro/
Searching for ContinentalHotels in the Search Bar.
Click the text/link under the company's logo
Trying to make a responsive test by reducing the size of the screen at maximum my laptop allowed.
When rescaling the screen ( after I enlarge again the screen) the graphic remains in his small size.
See atachment.

Expected result:
After rescaling the screen, all the design should be normal, everything at the normal size.

Actual result:
After enlarging the screen the graphic of the job's number remained in small size. See the attachement below.
![the_small_graphic_bug](https://github.com/peviitor-ro/Scrapers-UI/assets/129604131/af67d1bb-2a3c-4292-98ca-6983bc8397d2)

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
