### ISSUE TITLE
Penny - Graph does not update after refreshing the page 

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#431]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/penny/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Wait for the scraper to load the jobs
4) Refresh the page
5) Check graph

EXPECTED RESULTS:
Last date in the graph is current date (09.12.2023)

ACTUAL RESULTS:
Last date in the graph is 20.11.2023

![a1](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/3b22ca24-1521-4a7d-b637-a19faa523693)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest graph work correctly
