### ISSUE TITLE
Autonom - 'Vezi postul' button is displayed in red instead of green

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#432]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/autonom/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check 'Vezi postul' button under jobs

EXPECTED RESULTS:
The button name is displayed in green

ACTUAL RESULTS:
The button name is displayed in red

![a2](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/7d23e4f5-29e8-40ab-8322-88b326d0baa2)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest 'Vezi postul' button is displayed in green
