### ISSUE TITLE
Samsung- Status Inactive

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#435]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open the URL in the browser
2) Search for "Samsung" Company
3) Run scraper
4) Check the "Status" section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section

![a4](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/2e614eb9-9462-42b1-b82b-658a81a4c7a4)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the status is active
