### ISSUE TITLE
Evozone- Graph without active data

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#436]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open the URL in browser
2) Search for 'Evozone' Company
3) Click on 'Run scraper' button
4)Check the graph functionality

EXPECTED RESULTS:
The graph is active, it shows the number of valid jobs in the last few days

ACTUAL RESULTS:
Graph without active data

![a5](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/bc0ca561-923b-42f7-8790-13e7803ff896)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest the graph have active data
