### ISSUE TITLE
Webasto- Missing LOGO

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#437]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Search for 'Webasto' Company
3) Check logo

EXPECTED RESULTS:
The logo of the company Webasto is the same as the logo found on company website

ACTUAL RESULTS:
The company logo is missing from scrapers.peviitor.ro

![a6](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/9f6c92c3-222d-4a3c-adf9-9da314ed2f03)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest the company logo is displayed
