### ISSUE TITLE
Cargotrack - Missing " Targetare .ro" button

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#440]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Cargotrack  " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"

EXPECTED RESULTS:
The "Targetare.ro" button is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/23b753b5-1c48-4875-a818-a4a12b85bf9e)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" button is functional and the page is opened.
