### ISSUE TITLE
Calcrom - Missing " Targetare .ro" button

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#442]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Calcrom " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro".

EXPECTED RESULTS:
The "Targetare.ro" button is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/dce60563-07c8-46d6-a2e8-5737bb4a4295)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" button is functional and the page is opened.
