### ISSUE TITLE
Nefab - peviitor logo missing from page

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#443]
COMPANY: Nefab
URL: [Nefab peviitor.ro](https://scrapers.peviitor.ro/src/nefab/index.html)
Company's Career website: [Nefab official website](https://www.nefab.com/en/careers/job-opportunities/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/nefab/index.html) must be open in browser.

Steps:

1. **Observe** the logo on the top left corner of the page.
2. **Click** the Refresh button
3. **Observe** the results.

Expected results:
The logo peviitor schould appear next to "Scraper-UI." text.

Actual result:
Peviitor logo is not visible on the page.

<img width="654" alt="Screenshot 2023-12-11 at 12 10 50" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/4ae4984b-0278-4019-b1e9-c187e085e2e2">

<img width="299" alt="Screenshot 2023-12-11 at 12 14 57" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/63da74cc-5b66-46eb-8d58-4792996df75b">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by iBixee** [comment]
Thanks!
