### ISSUE TITLE
Expertmind -  " Targetare .ro" button exists, without leading to a link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#446]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Expertmind " Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro".

EXPECTED RESULTS:
The "Targetare.ro" button is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" button.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/96e88748-dc8c-446a-9f0e-84f904bb9f37)

**Comment by lalalaurentiu** [comment]
The company is not present on targetare.ro. This issue will not be fixed
