### ISSUE TITLE
Adecco - Logo is missing

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#448]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/adecco/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter Adecco in the search bar.
3. Click the button under the company's logo.
4. The company-specific scraper page opens.

Expected result:
The company logo appears in the body of the page.

Actual result:
The company logo does not appears in the body of the page.

<img width="834" alt="Screenshot at Dec 11 13-56-58" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/6f23c871-4f39-4eae-bd1b-7ead59d37257">

**Comment by AdelinaGuliman** [comment]
The problem persists. Make sure you are using the Safari browser
<img width="822" alt="Screenshot at Dec 15 13-39-05" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/6ed22676-31c8-49f7-923e-c1181b71794e">

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
