### ISSUE TITLE
Adecco - "Run Scraper" button  load failed

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#449]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/adecco/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter Adecco in the search bar.
3. Click the button under the company's logo.
4. Click the button "Run Scraper".

Expected result:
The scraper is updating

Actual result:
Load failed.

<img width="1404" alt="Screenshot at Dec 11 14-05-45" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/478757d0-2b1d-4867-a02d-6c936d8e0e80">

**Comment by lalalaurentiu** [comment]
Fixed
