### ISSUE TITLE
Adecco - Graphic design error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#450]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/adecco/)
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Safari browser.

Steps:
1. Click on Firme from footer.
2. Enter Adecco in the search bar.
3. Click the button under the company's logo.
4. Right click in the body of the page and select the "Inspect Element" option
5. Close the "Inspect Element" option

Expected result:
The graphic on the cover of the page returns to its original form

Actual result:
The graphic on the cover of the page does not returns to its original form

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/28b2a439-6329-4283-982e-56fd72a97514

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
