### ISSUE TITLE
Avangardesoftware- Graph without active data

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#451]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Search for 'Avangardesoftware' Company 
3) Click on 'Run scraper' button
3) Check the graph functionality

EXPECTED RESULTS:
The graph is active, it shows the number of valid jobs in the last few days

ACTUAL RESULTS:
Graph without active data

![a10](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/80ee27f8-75af-4a16-b198-c6aa5e16e349)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the graph has active data
