### ISSUE TITLE
Strabag- Scraper does not recognize Ramnicu Valcea as a city in Romania

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#452]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/strabag/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check location for 'Project Manager Comercial' job

EXPECTED RESULTS:
Ramnicu Valcea is recognized as a city in Romania for 'Project Manager Comercia' job

ACTUAL RESULTS:
The Scraper does not recognize Ramnicu Valcea as a city in Romania and displays 'Ramnicu Valcea is not a city in Romania'

![a11](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/9b7041fe-8f89-43af-9c2a-2e85b44673bc)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting Ramnicu Valcea is recognized as a city in Romania
