### ISSUE TITLE
Ptc- Missing Targetare.ro link

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#453]
ENVIROMENT: production
URL: 
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Go to company logo
3) Check for Targetare.ro link

EXPECTED RESULTS:
Targetare.ro link is visible and opens

ACTUAL RESULTS:
Targetare.ro link for Ptc company does not exist

![a12](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/cf59fd95-5ddd-4def-b442-9157e24893e9)

**Comment by lalalaurentiu** [comment]
the company is not present on targetare.ro
