### ISSUE TITLE
Bbcollection - Missing "Targetare.ro" button's functionality

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#454]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Bbcollection" Company
3. Click on the "Targetare.ro" link

EXPECTED RESULTS:
The "targetare.ro" link  is functional and the page is opened.

ACTUAL RESULTS:
"Targetare.ro" link is not functional.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/98723f0d-1077-4433-b6d5-77c6e649db94)

**Comment by lalalaurentiu** [comment]
The company is not present on targetare.ro. This issue will not be fixed
