### ISSUE TITLE
Megaimage - Page not found at GitHub Repo. Page error message

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#455]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
Browser: Google Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "Megaimage" Company
3.Run scraper
4.Click on Github Repo.

EXPECTED RESULTS:
The https://github.com/peviitor-ro/based_scraper_py/blob/main/sites/MegaImage.py should be open in the browser

ACTUAL RESULTS:
The message "404 - page not found" is displayed 

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/fb5a1227-a757-47a2-b051-4ae7ae41c613)

**Comment by lalalaurentiu** [comment]
Fixed
