### ISSUE TITLE
Basware - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#456]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Basware " Company
3. Click on the "Targetare.ro" link.

EXPECTED RESULTS:
The "targetare.ro" link is functional and the page is opened.

ACTUAL RESULTS:
"Targetare.ro" link is not functional.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/24ff0abe-1c97-4a96-91e4-49718b077910)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested, The "targetare.ro" link is functional and the page is opened.
