### ISSUE TITLE
Avaelgo - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#458]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Avaelgo " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link

EXPECTED RESULTS:
The "targetare.ro" link is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" link

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/9d94ca95-2459-4eec-96c6-920794ed8547)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested, The "targetare.ro" link is functional and the page is opened.
