### ISSUE TITLE
Mazars - Missing "Targetare.ro" button

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#459]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for "Mazars " Company
3.Go to logo - Click on Targetare.ro
4.Verify "Targetare.ro" button

EXPECTED RESULTS:
The "Targetare.ro" button is functional . Targetare link opens correctly

ACTUAL RESULTS:
Missing "Targetare.ro" button. Targetare link doesn't open targetare.ro

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/4e5833f8-540d-4dcb-85f7-516e3766934b)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Data is now correct after fixing the bug.

But verify this one: The number of jobs on scrapers peviitor.ro (26) is not the same as the number of jobs peviitor.ro (24).

**Comment by lalalaurentiu** [comment]
check on "targetare.ro" if it exists
