### ISSUE TITLE
Altom - missing the number of jobs on the Graph

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#460]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Run scraper for "Altom" Company 
3.Check the number of jobs on the graph

EXPECTED RESULTS:
The number of jobs should be displayed on the graph

ACTUAL RESULTS:
The scraper doesn't displayed jobs number for the "Altom" Company

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/c8f5ca07-4530-4e6b-8130-162e9925d742)

**Comment by lalalaurentiu** [comment]
Fixed
