### ISSUE TITLE
HCLTechnologies - Graph without active data and message error

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#463]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Run scraper for "Hcltechnologies" Company 
3.Verify the number of jobs on the Graph
4.Verify the "status" section
5.Click on Github Repo.

EXPECTED RESULTS:
The Graph  is active, it shows the number of valid jobs in the last few days
The scraper runs correctly and the message "Active" is displayed in the "Status" section
The https://github.com/peviitor-ro/based_scraper_py/blob/main/sites/hcltechnologies.py should be open in the browser
 The jobs from Romania are displayed on the company's website!

ACTUAL RESULTS:

Graph without active data
The scraper does not displayed activ Status. The "database" message is displayed in the "Status" section
The scraper returned message: "TypeError: Failed to fetch; Gettin data from peviitor database!"
The message "404 - page not found" is displayed 
The company jobs  are not returned by the scraper 

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/6e714136-3bfb-4f24-9882-323feea51e91)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
1. Retesting.  The bug is no longer reproducible with the initial steps.
Data is now correct and consistent after fixing the bug.

2. Retesting. Run scraper. Discover new bug:

Check for this jobs, the locations of the city aren't displayed:

Cloud Engineer
Frontend Developer with Vue
.NET Developer
Frontend Developer with Angular
Linux Cloud DevOps Engineer
SAP FICO Consultant
Microsoft Dynamics 365 F&SCM Developer
SAP Basis Consultant with German
Spark Developer
Technical Support
Frontend Developer with React
Frontend Developer with Angular
.Net Developer
QA Automation Engineer
DevOps Engineer
Golang Developer
Rust Developer
Solution Architect
Sitecore Developer
Full Stack Developer
Delivery Manager
Java Developer
Product Owner

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/66e20b5a-3db7-4a08-a3b6-3c1f683e3bd7)
