### ISSUE TITLE
Autosiena - Missing "Targetare.ro" link's functionality

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#464]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Autosiena" Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link

EXPECTED RESULTS:
The "targetare.ro" link is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" link

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/795c91cf-4668-4912-90d6-5e4bdfda8d99)

**Comment by lalalaurentiu** [comment]
The company is not present on targetare.ro. This issue will not be fixed
