### ISSUE TITLE
Autonet - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#465]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Autonet " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link

EXPECTED RESULTS:
The "targetare.ro" link is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" link

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/f399dceb-6302-4fca-9670-c4f19368b10c)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested, The "targetare.ro" link is functional and the page is opened.
