### ISSUE TITLE
Hamilton - Targetare.ro button is missing its functionality

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#468]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check "Targetare.ro" buttons

EXPECTED RESULT:
To see the webpage Targetare.ro with data from the company.

ACTUAL RESULT:
The button is missing.

![Screenshot_1](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/ba212b07-3ddc-4d18-8cc1-75db81c5d115)

**Comment by lalalaurentiu** [comment]
The company is not present on targetare.ro. This issue will not be fixed
