### ISSUE TITLE
Dm - Logo Scrapper-UI not working

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#469]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check logo Scrapper-UI

EXPECTED RESULT:
You can see the logo

ACTUAL RESULT:
You can't see the logo and in the inspect console you have a 404 status.
![Screenshot_5](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/00a07d4c-243f-4f57-9da1-fbbd9753fac8)

**Comment by lalalaurentiu** [comment]
Fixed!
