### ISSUE TITLE
Hamilton- Logo Scrapper-UI missing

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#470]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check logo Scrapper-UI

EXPECTED RESULT:
You can see the logo

ACTUAL RESULT:
You can't see the logo and in the inspect console you have a 404 status.

![Screenshot_6](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/4f3202c0-724e-456d-80b0-b30c9d36c6ea)

**Comment by lalalaurentiu** [comment]
Fixed!
