### ISSUE TITLE
Hamilton - The details are a hyperlink

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#471]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check the details

EXPECTED RESULT:
You can see the details without the link.

ACTUAL RESULT:
All the details are a hyperlink with Hamilton webpage.

![Screenshot_7](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/c9a11391-cf7b-412e-9d41-569a8d4af17e)

**Comment by lalalaurentiu** [comment]
I don't see any problem
![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/183c22a6-914a-497c-b8ec-ab6f752e8b07)
