### ISSUE TITLE
Hamilton - The "Run scrapper" error

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#472]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check Run Scraper button

EXPECTED RESULT:
When you click on the button, you can see the date of the jobs.

ACTUAL RESULT:
When you click on the button, you are It will take you to the Hamilton web page, after you will see the "Inactive" Status.
The button is too big compared to the other buttons.

![Screenshot_7](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/dba7f8be-9925-4266-a498-a60ae34ddfc8)

**Comment by lalalaurentiu** [comment]
I don't see any problem
![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/4fe3f26d-9071-4125-8c0a-a52b3034cdfd)
