### ISSUE TITLE
Atp-group -  Graph without active data for the jobs on; - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#474]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Atp-group " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link.
5. Check the graph functionality.

EXPECTED RESULTS:
The "Targetare.ro" link is functional and the page is opened.
The Graph  have active data and show the number of valid jobs.

ACTUAL RESULTS:
Missing "Targetare.ro" link
Graph without active data for the jobs on.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/4672db3e-9f45-4314-bd3d-96a72112cde3)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro.
Fixed graphic

**Comment by Geo843** [comment]
Re-tested,  The Graph have active data and show the number of valid jobs.
