### ISSUE TITLE
Veoneer- Targetare.ro link should be deleted

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#475]
![q1](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/308c3987-0916-45c1-bb13-ab6bd0cb5a00)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting Targetare.ro link for Veoneer is deleted
