### ISSUE TITLE
Adobe- Missing location for 'Territory Account Manager'

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#477]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Run scraper for 'Adobe' company
3) Check location for 'Territory Account Manager' job
4) Click on 'Vezi postul' button below 'Territory Account Manager' job
5) Check location 

EXPECTED RESULTS:
The location for 'Territory Account Manager' job should be the same as the location on company website( Bangkok)

ACTUAL RESULTS:
The location for 'Territory Account Manager' job is 'No city'
**Note**: The bug also reproduce for: 
-Enterprise Sales Account Manager
-Sales Account Manager, Mid Market

![a16](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/9160aa6f-d7ac-4d9d-921d-e2f081caba7d)

**Comment by lalalaurentiu** [comment]
Fixed!
