### ISSUE TITLE
Adobe- Remote was written in the location section instead of in the job type section for 45 jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#484]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Run scraper for 'Adobe' company
3) Check the location of jobs where remote is listed

EXPECTED RESULTS:
Remote should be written in job type section not in location section

ACTUAL RESULTS:
Remote it is written in location section instead of job type section
For 1 job 'Remote is not a city in Romania' is displayed

![a15](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/3dff51c1-45b9-4f5d-911c-31952d65b288)
![a17](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/f23e5d42-b1d0-4313-8bd9-905c66f194ce)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting 1 job has "Remote ACT" written in the location section 


![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/87a884f7-0f74-4396-96ca-29dd1948abe8)

**Comment by lalalaurentiu** [comment]
Fixed
