### ISSUE TITLE
Acrom - Missing "Targetare.ro" button

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#488]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Acrom" Company
3.Go to logo - Click on Targetare.ro
4.Verify "Targetare.ro" button

EXPECTED RESULTS:
The "Targetare.ro" button is functional . Targetare link opens correctly

ACTUAL RESULTS:
Missing "Targetare.ro" button. Targetare link doesn't open targetare.ro

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/89f77825-b7b6-48f0-817a-57dd0302400b)

**Comment by lalalaurentiu** [comment]
the company is not present on targetare.ro
