### ISSUE TITLE
Docker -  Missing "Targetare.ro" button

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#489]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for "Docker" Company
3.Go to logo
4.Verify "Targetare.ro" button

EXPECTED RESULTS:
The "Targetare.ro" button is functional . Targetare link opens correctly

ACTUAL RESULTS:
Missing "Targetare.ro" button. Targetare link doesn't open targetare.ro

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/1286fc91-b436-4554-bc9a-5aab45f0ef13)

**Comment by lalalaurentiu** [comment]
the company is not present on targetare.ro
