### ISSUE TITLE
MagnaElectronics - Missing graphic date

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#490]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Run scraper for "MagnaElectronics" Company 
3.Check the number of jobs on the graph

EXPECTED RESULTS:
The number of jobs should be displayed on the graph

ACTUAL RESULTS:
The scraper does not displayed jobs number for the Company on the graph

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/6b9ea3aa-5135-4a32-acce-d3e7de480af9)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdinaIT** [comment]
1. Validating the bug fix for the first problem.
2. Run scraper. 
3. For this job "Engineering Supplier Manager", at the city section "Romania is not a city in Romania" is displayed.
