### ISSUE TITLE
Farmaciatei - "Inactive" status; Graph without active data;  No data in Local Storage

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/Scrapers-UI#491]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "Farmaciatei" Company
3.Run scraper
4.Check the "Status" section
5.Check Graph
6. Check Local Storage

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section
The Graph displays the data on the cover of the page
Local Storage display all data

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section
The graphic on the cover of the page does not returns the data
The scraper does not return data in Local Storage

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/127322865/5132ce87-caa8-493e-8795-68c1b79d793e)

**Comment by lalalaurentiu** [comment]
This scraper was removed
