### ISSUE TITLE
Visa - "Careers" link invalid

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#493]
ENVIROMENT: production
COMPANY: Visa
URL: [Visa scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/visa/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Visa in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo.
5. Click on the "Careers" button.

Expected result:
The official page of the company opens, showing the number of available jobs from Romania.

Actual result:
The official page of the company opens, showing the availability of the job From Poland, Türkiye and Ukrainka.

https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/a55389d9-211e-4e85-9f20-5646a3daf1b6

**Comment by lalalaurentiu** [comment]
Fixed
![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/06fceeb6-26f0-48dd-8dc8-7fd97bdc7f84)
