### ISSUE TITLE
Retarus - The "Careers" link is wrong

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#494]
ENVIROMENT: production
COMPANY: Retarus
URL: [Retarus scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/P&G/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter Retarus in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo.
5. Click on the "Careers" button.

Expected result:
The official page of the company opens, showing the number of available jobs

Actual result:
The official page of the company opens, showing the availability of the job with the title "Become EDI Support Analyst (m/f/d)"

https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/958b4ae7-f30f-4ced-a45c-d96c142b8f15

**Comment by lalalaurentiu** [comment]
Fixed!
