### ISSUE TITLE
Allengra - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#503]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Allengra  " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link

EXPECTED RESULTS:
The "Targetare.ro" link is functional and the page is opened.

ACTUAL RESULTS:
Missing "Targetare.ro" link

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/f23bfd8d-ede3-4f97-8fa7-5b303b55161f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" link is functional and the page is opened.
