### ISSUE TITLE
Aeroportoradea - Missing "Targetare.ro" link ; -Graph without active data for the jobs on

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#504]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Aeroportoradea " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link.
5. Check the graph functionality

EXPECTED RESULTS:
1. The "Targetare.ro" link is functional and the page is opened.
2. The graph have active data and show the number of valid jobs

ACTUAL RESULTS:
1. Missing "Targetare.ro" link
2. Graph without active data, doesn't show the number of valid jobs

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/395ac235-5de7-49e9-ae1e-e2bf83dbfc22)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro

**Comment by Geo843** [comment]
Re-tested, The graph have active data and show the number of valid jobs
