### ISSUE TITLE
Bioclinica - clicking on "Bioclinica Careers"  does not open  "Bioclinica Careers" website

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/Scrapers-UI#509]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "Bioclinica" Company
3. Click on "Bioclinica" 
4. Hover over "Bioclinica" Logo
5. Click on "Bioclinica Careers"

EXPECTED RESULTS:
By clicking on "Bioclinica Careers" should open  "Bioclinica Careers" website

ACTUAL RESULTS:
"Bioclinica Careers" does not open  "Bioclinica Careers" website

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by RaresCode** [comment]
Can you retest?

**Comment by MarinaCosmina** [comment]
Re-teste, Careers button opens Bioclinica Career page.
