### ISSUE TITLE
 Mennekes - Missing "Targetare.ro" link; - Graph without active data for the jobs on

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers-UI#511]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "  Mennekes " Company
3. Click on the "Targetare.ro" link
4. Open "Targetare.ro" link.
5. Check the graph functionality

EXPECTED RESULTS:
The "Targetare.ro" link is functional and the page is opened.
The graph have active data and show the number of valid jobs

ACTUAL RESULTS:
Missing "Targetare.ro" link
Graph without active data, doesn't show the number of valid jobs

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/e325ede7-6027-4c95-a622-4170e1e6aac9)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested, The "Targetare.ro" link is functional and the page is opened.
The graph have active data and show the number of valid jobs
