### ISSUE TITLE
BRD- 'Romania is not a city in Romania' is displayed in city section for all jobs

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#515]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Run scraper for "BRD" company
3) Check the city section for all jobs

EXPECTED RESULTS:
In the city section should be a city not a country

ACTUAL RESULTS:
In the city section "Romania is not a city" is displayed

![a23](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/92679f28-8ef2-4ca7-aa73-90600532b662)

**Comment by lalalaurentiu** [comment]
fixed on pull request [434](https://github.com/peviitor-ro/Scrapers-UI/pull/434/commits/0984c31a984fc064a0d3e7b5350bf5c609962e9f).
Re-test after pull request is merged.
