### ISSUE TITLE
Vodafone- Drobeta-Turnu Severin is not recognized as a city in Romania 

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers-UI#516]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/vodafone/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check location for 'Sales Advisor' where Drobet-Turnu Severin is not recognized as a city in Romania

EXPECTED RESULTS:
Drobeta-Turnu Severin should be recognized as a city in Romania

ACTUAL RESULTS:
The Scraper does not recognize 'Drobeta-Turnu Severin' as a city in Romania and displays 'Drobeta-Turnu Severin is not a city in Romania'

![a24](https://github.com/peviitor-ro/Scrapers-UI/assets/72222644/fac49a67-c140-4057-a49a-ace7d507a541)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting Drobeta-Turnu Severin is recognized as a city in Romania
