### ISSUE TITLE
Missing graph - Wizzair

### ISSUE THREAD

**Issue by Mede375** [peviitor-ro/Scrapers-UI#518]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Computer
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for "WizzAir " Company

EXPECTED RESULTS:
The graph must be displayed and functional. 

ACTUAL RESULTS:
The graph is missing. 
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/144273209/1cb82cdc-24b9-4e71-b4c8-ccfbe88d8126)

**Comment by lalalaurentiu** [comment]
Fixed
