### ISSUE TITLE
The logo is missing - Wayfare

### ISSUE THREAD

**Issue by Mede375** [peviitor-ro/Scrapers-UI#520]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Computer
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for "Wayfare " Company

EXPECTED RESULTS:
The logo must be displayed.

ACTUAL RESULTS:
The logo is missing.
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/144273209/ee147ec9-780e-4107-a9cf-fbee95ee5409)

**Comment by lalalaurentiu** [comment]
Fixed
