### ISSUE TITLE
ASSA ABLOY - Error 404 on Targetare.ro link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#527]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the[ URL](https://scrapers.peviitor.ro/src/assaabloy/index.html) in the browser
2. Run scraper for "Assa Abloy" Company
3. Go to logo
4. Click on "Targetare.ro" button

EXPECTED RESULTS:
The Targetare.ro website opens and the relevant information on the company is displayed.

ACTUAL RESULTS:
The Targetare.ro website opens, but the message "Eroare 404 - Ne pare rău, dar pagina pe care o cauți nu există" is displayed.

Also, I should mention that the company actually exists on targetare.ro under the name Assa Abloy Opening Solutions Romania SRL, located in Bucharest, B-dul Preciziei.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/40c2e88a-7191-4cd0-8f1c-f6b65f6e64c2)

**Comment by lalalaurentiu** [comment]
check on "targetare.ro" if it exists

**Comment by Sarra113** [comment]
It exists. I retested and the link seems to be working now, so I will close the issue.


https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/a6461e1b-b682-402c-b970-19f201a285d8
