### ISSUE TITLE
BAYWA R.E. - Error 404 on Targetare.ro link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#531]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the [URL](https://scrapers.peviitor.ro/src/bayware/index.html) in the browser
Run scraper for "Baywa r.e." Company
Go to logo
Click on "Targetare.ro" button

EXPECTED RESULTS:
The Targetare.ro website opens and the relevant information on the company is displayed.

ACTUAL RESULTS:
The Targetare.ro website opens, but the message "Eroare 404 - Ne pare rău, dar pagina pe care o cauți nu există" is displayed.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/b8d707cf-33f3-4bf4-8c88-bf528f29b163)

**Comment by lalalaurentiu** [comment]
check on "targetare.ro" if it exists

**Comment by Sarra113** [comment]
I think this is it: https://targetare.ro/48228888/baywa-re-romania-srl 
The careers link doesn't work either and there are no jobs available in Romania, but the location on Targetare matches the one on the company's website.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/67972b56-e425-4c90-8b3b-24b5e05f9132)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/24d024b2-62fa-4383-838c-fa97021920aa)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Sarra113** [comment]
Retested ✅
