### ISSUE TITLE
BAYWA R.E.  - Careers link not working

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#532]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the [URL](https://scrapers.peviitor.ro/src/bayware/index.html) in the browser
Run scraper for "Baywa r.e." Company
Go to logo
Click on "Careers" button

EXPECTED RESULTS:
The company's website opens on the careers section.

ACTUAL RESULTS:
The  website cannot be found and an error occurs. 

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/1d8bed25-4c70-42cf-95ef-601410d97b26)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
Retested ✅
