### ISSUE TITLE
Grubhub -"Targetare.ro" does not open

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#534]
ENVIROMENT: production
COMPANY: Grubhub
URL: [Grubhub scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/grubhub/index.html)
Browser: Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Chrome browser.

Steps:
1. Click on Firme from footer.
2. Enter Grubhub in the search bar.
3. Click the button under the company's logo.
4. Place the cursor on the company logo
5. Click on "Targetare.ro".

Expected result:
The "Targetare.ro" opens.

Actual result:
The "Targetare.ro" does not open.

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/afc2517a-bbbe-4f40-a244-e60db0a63d32

**Comment by lalalaurentiu** [comment]
check on "targetare.ro" if it exists
