### ISSUE TITLE
FlTechincs - Error 404 "Page Not Found"

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#535]
ENVIROMENT: production
COMPANY: FlTechincs
URL: [FlTechincs peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter FlTechincs in the search bar.
Click the button under the company's logo.

Expected result:
The Scraper-UI related to the company opens.

Actual result:
Error 404 "Page Not Found"

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/e8f871b1-1052-4b09-aee4-2b69b2a4e0f9

**Comment by lalalaurentiu** [comment]
Fixed
