### ISSUE TITLE
Safari ALL - Logos are blurred and Carrers and Targetare buttons are mirrored

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#538]
ENVIROMENT: production
COMPANY: All
URL: https://scrapers.peviitor.ro
Browser: Safari
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro) must be open in browser.

Steps:

1. Select and click on the companies names on the page.
2. Observe the logo box on the page.
3. Hover over the logo box and observe the changes.

Expected result:
Company logo should appear on the designated box on the page.
By hovering over it should turn and display Careers and Targetare(if exists) buttons.

Actual result:
Logos are blurred. 
The logos are overlapping with the Careers and Targetare buttons.
Careers and Targetare buttons are mirrored.

<img width="785" alt="Screenshot 2024-01-10 at 22 57 20" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/d89eb35b-1a22-4a8a-9e3c-66b3164526ce">

<img width="787" alt="Screenshot 2024-01-10 at 22 57 28" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/c6386d6e-da1c-49ab-b4e7-596cb8f39aba">

**Comment by lalalaurentiu** [comment]
the bug will be fixed when the validator appears

**Comment by iBixee** [comment]
Got it! Thank you!
