### ISSUE TITLE
Stericycle - Targetare link is listing another company's data

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/Scrapers-UI#544]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
**Company_careers_url**: [Stericycle](https://scrapers.peviitor.ro/src/stericycle/index.html)
 Desktop:
```
OS: IOS
Browser: Safari
Version: 14.2.1 
```

 
### **STEPS TO REPRODUCE:**
1) **Write** "Stericycle" in the search bar 
2) **Click** on the company folder
3) **Hover** over the company logo box
4) **Click** the "Targetare" button
5) **Observe** the companies names

>**EXPECTED RESULTS:**
Targetare link should list the company data.

>**ACTUAL RESULTS:**
Targetare link is listing data from a different company.
<br>

**Screenshots**

<img width="791" alt="Screenshot 2024-01-12 at 19 05 17" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/2a9d08e3-6b39-4306-bb70-3d1694dd9a51">

**Comment by lalalaurentiu** [comment]
Verifica siteul ce este prezent in targetare si ai sa vezi ca asta e firma 
![Screenshot 2024-01-29 at 14 46 00](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/269ae35e-a209-4d0b-86de-7659d6d50b7c)

**Comment by iBixee** [comment]
Poate este o eroare a celor de la Targetare.ro. Google spune ca sunt doua firme diferite. Oricum cu un simplu search se poate afla usor. Thanks!
