### ISSUE TITLE
Adecco - The chart does not contain valid data

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#551]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/adecco/index.html)
Browser: Google Chrome
Device: phone
OS: Android

Precondition:
The [site](https://scrapers.peviitor.ro/src/adecco/index.html) must be open in Chrome browser.

Steps:
1. Click on Firme from footer.
2. Enter Adecco in the search bar.
3. Click the button under the company's logo.

Expected result:
The chart contains valid data

Actual result:
The chart does not contain valid data.
<img width="578" alt="Screenshot at Jan 16 15-13-54" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/4400366b-c0a4-4f1c-9b73-101d11c7d4dc">

**Comment by lalalaurentiu** [comment]
fixed when the validator is published
