### ISSUE TITLE
Assaabloy - Targetare.ro error 404

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#555]
ENVIROMENT: production
COMPANY: Assaabloy
URL: [Assaabloy targetare.ro](https://targetare.ro/10473502/assa-abloy-romania-srl)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in Google Chrome browser.

Steps:
1. Click on Firme from footer.
2. Enter Assaabloy in the search bar.
3. Click the button under the company's logo.
4. Put the cursor on the company logo.
5. Click on "Tragetare.ro" button

Expected result:
Targetare.ro page opens.

Actual result:
The Targetare.ro website gives us a 404 error
<img width="1189" alt="Screenshot at Jan 17 13-17-52" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/2a117d4a-18c6-41eb-91ea-ea2a547927c9">

**Comment by lalalaurentiu** [comment]
Fixed
