### ISSUE TITLE
Keyence - Can't see the jobs on the "See jobs" selection

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers-UI#556]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check See jobs button

EXPECTED RESULT:
When you click on the button, you can see the jobs.

ACTUAL RESULT:
When you click on the button, you can see 0 jobs.
![Screenshot_6](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/c505437f-2859-43a5-91d6-53e7e1383c24)
![Screenshot_7](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/4e416a03-a82e-410d-a1b0-98e4459f01d4)

**Comment by lalalaurentiu** [comment]
Fixed
