### ISSUE TITLE
Assaabloy - GitHubRepo button returns 404 error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#557]
ENVIROMENT: production
COMPANY: Assaabloy
URL: [Assaabloy scarpers.peviitor.ro](https://scrapers.peviitor.ro/src/assaabloy/index.html)
Browser: Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/assaabloy/index.html) must be open in Chrome browser.

Steps:
1. Click on Firme from footer.
2. Enter Assaabloy in the search bar.
3. Click the button under the company's logo.
4. Click the "GitHubRepo" button

Expected result:
The GitHub repository opens

Actual result:
The Github repository opens with a 404 error message.

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/aca1c9d3-d68c-4ee8-9c60-4386a78ac387

**Comment by lalalaurentiu** [comment]
Fixed
