### ISSUE TITLE
CGM - Missing Targetare link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#560]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/cgm/)
 2. Hover over the company's logo.

EXPECTED RESULTS:
  There is a 'Targetare' button (with link) just under the 'Careers' one.

ACTUAL RESULTS:
  The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/907cd4ee-00d2-465c-92dd-00f5f81bccc6)

**Comment by lalalaurentiu** [comment]
duplicate #420

**Comment by Sarra113** [comment]
Hi! 

Even if issue #420 was closed as the company was not on Targetare, I found it there and the information matches the one from the company's Romanian official website. https://targetare.ro/36268684/cgm-software-ro-srl

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/4d56ce02-d0b0-4c7a-872f-d5fc030036ab)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/900d4058-8ee4-4195-b9f1-c2428f5fd6d4)

**Comment by Sarra113** [comment]
The issue is still there:

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/9e72aca6-6216-4bf3-b92c-e4e199c2c259)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
Retested ✅
