### ISSUE TITLE
Verla -Missing company LOGO and the MESSAGE "Bucuresti, Cluj-Napoca, Iasi is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#562]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for the company "Verla"
3.Check the logo.
4.Open "Run Scrapers" button
5.Check the job locations.

EXPECTED RESULTS:
The " Verla Company" logo is there and is functional.
Job locations should be the same on Scrapers-UI as on the company website.

ACTUAL RESULTS:

Error LOGO on the scrapers.peviitor.ro
The message "Bucuresti, Cluj-Napoca, Iasi is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![verla_logo](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/aa385e94-3d20-4724-95b1-196b16a84306)
![Verla_loc](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/3140b783-fcfd-4181-b917-7a3297b8ca62)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Aniod01** [comment]
Retested
