### ISSUE TITLE
INOVA - Missing "Targetare" link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#563]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the [url](https://scrapers.peviitor.ro/src/inova/index.html)
2. Hover over the company's logo.

EXPECTED RESULTS:
There is a 'Targetare' button (with link) just under the 'Careers' one.

ACTUAL RESULTS:
The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/f74fa7be-1eed-480d-b78b-a0e489a67305)

**Comment by lalalaurentiu** [comment]
Fixed
