### ISSUE TITLE
NOODLEPACK - The company doesn't exist on Scrapper.UI

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#565]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the url
2. Type "noodlepack" in search field

EXPECTED RESULTS:
Should have a result with Noodlepack company

ACTUAL RESULTS:
Noodlepack company doesn't exist on Scraper.UI

Attachments:
![noodlepackui](https://github.com/peviitor-ro/Scrapers-UI/assets/63416053/d15de9eb-d8f7-4899-ba6b-f61eb7302f7e)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Aniod01** [comment]
Retested
