### ISSUE TITLE
BASWARE - Missing company logo on scrapers.peviitor.ro

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#567]
ENVIRONMENT: production

Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the [url](https://scrapers.peviitor.ro/src/basware/index.html)

EXPECTED RESULTS:
The company logo is visible in the square in the center.

ACTUAL RESULTS:
The company logo is missing from the center of the page.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/10a6f7a7-087e-4a6a-97d4-6a402fdd12e8)

**Comment by lalalaurentiu** [comment]
fixed
