### ISSUE TITLE
ORADEATECHHUB- Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#568]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/oradeatechhub/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2. Go to company logo
3. Check for Targetare.ro link

EXPECTED RESULTS:
Targetare.ro link is visible and opens

ACTUAL RESULTS:
Targetare.ro link for oradeatechhub company does not exist

ATTACHMENTS:
![oradea](https://github.com/peviitor-ro/Scrapers-UI/assets/63416053/cfe34733-b1bd-46ab-be13-ebae37ac4c90)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Aniod01** [comment]
Retested.
