### ISSUE TITLE
Typingdna - Logo is missing and the careers section on the Typingdna official website is not opened

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#569]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "typingdna"
3. Check the logo.
4. Hover over the logo and click on Typingdna Careers.

EXPECTED RESULTS:

1. The "Typingdna Company" logo is there and is functional.
2. The careers section on the Typingdna official website is open in browser.

ACTUAL RESULTS:

1. Error LOGO on the scrapers.peviitor.ro
2. Instead the careers section on the Typingdna official website is open the [url](https://scrapers.peviitor.ro/src/typingdna/index.html#)

ATTACHMENTS:
![typindga](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/407ee4be-9d6f-424f-b325-e7e787e8d9d7)
![typindgaCareers](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/d574b259-5c44-4bbf-af51-0c292ce4e795)

**Comment by lalalaurentiu** [comment]
fixed
