### ISSUE TITLE
Jobshop - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#573]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/jobshop/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2. Go to company logo
3. Check for Targetare.ro link

EXPECTED RESULTS:
Targetare.ro link is visible and opens

ACTUAL RESULTS:
Targetare.ro link for jobshop company does not exist
![jobshoptargetare](https://github.com/peviitor-ro/Scrapers-UI/assets/63416053/18f5f048-cfbd-4c1d-815e-bc46b509b31c)

ATTACHMENTS:

**Comment by lalalaurentiu** [comment]
firma nu este prezenta pe targetare.ro
