### ISSUE TITLE
HTECGroup - Missing "Targetare" link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#575]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

**STEPS TO REPRODUCE:**

1. Open the [url](https://scrapers.peviitor.ro/src/htecgroup/index.html)
2. Hover over the company's logo.

**EXPECTED RESULTS:**
There is a 'Targetare' button (with link) just under the 'Careers' one.

**ACTUAL RESULTS:**
The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/da2360e3-1760-49b5-8eaa-6def6aaf24e7)

**Comment by lalalaurentiu** [comment]
fixed
