### ISSUE TITLE
Aeroportoradea - Missing "Targetare.ro" link

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#577]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/aeroportoradea/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2. Go to company logo
3. Check for Targetare.ro link

EXPECTED RESULTS:
Targetare.ro link is visible and opens

ACTUAL RESULTS:
Targetare.ro link for Aeroportoradea company does not exist

ATTACHMENTS:
![aeropOradea](https://github.com/peviitor-ro/Scrapers-UI/assets/63416053/123f9a20-84e9-40c5-bfb0-ca61aed48dab)

**Comment by lalalaurentiu** [comment]
duplicate #504
