### ISSUE TITLE
DUKTECH - The careers link does not take you to the carrers section on the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#581]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the [url](https://scrapers.peviitor.ro/src/duktech/index.html)
Hover over the company's logo.
Click on "Duktech careers".

EXPECTED RESULTS:
You are redirected to the careers section on the company's official website.

ACTUAL RESULTS:
You are redirected to the main page of the company's website.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/ce8ece1a-4347-42e9-b6cf-429e5dd89af6)

**Comment by lalalaurentiu** [comment]
fixed
