### ISSUE TITLE
C-SCALE - Missing "Targetare" link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#582]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the [url](https://scrapers.peviitor.ro/src/cscale/index.html)
Hover over the company's logo.

EXPECTED RESULTS:
There is a 'Targetare' button (with link) just under the 'Careers' one.

ACTUAL RESULTS:
The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/e72f94a4-9cbd-4cb2-81d1-e48d953598a2)

**Comment by lalalaurentiu** [comment]
duplicate #404

**Comment by Sarra113** [comment]
Hi! 

I saw that #404 was closed because the company was not registered on Targetare.ro. After searching, I found it on Targetare and information there matches the one on the company's official website. https://targetare.ro/33201612/c-scale-software-srl

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/287c8074-38ca-4ebb-9dda-37f616eab43f)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/2a4c7966-1833-4ff9-896b-bede21b061f7)

**Comment by lalalaurentiu** [comment]
give me that link please

**Comment by lalalaurentiu** [comment]
reopen the issues

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Sarra113** [comment]
Retested ✅
