### ISSUE TITLE
EDUTRUST - Missing "Targetare" link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#583]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/edutrust/index.html)
Hover over the company's logo.

EXPECTED RESULTS:
There is a 'Targetare' button (with link) just under the 'Careers' one.

ACTUAL RESULTS:
The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/0b19ae20-85e1-4520-a628-d0d937834849)

**Comment by lalalaurentiu** [comment]
fixed
