### ISSUE TITLE
Tcandc - Missing "Targetare" link

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/Scrapers-UI#586]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/tcandc/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2. Go to company logo
3. Check for Targetare.ro link

EXPECTED RESULTS:
Targetare.ro link is visible and opens

ACTUAL RESULTS:
Targetare.ro link for tcandc company does not exist

Attachments:
![tcandc](https://github.com/peviitor-ro/Scrapers-UI/assets/63416053/8af773fa-19d7-4c45-91f5-bda594a9b586)

**Comment by lalalaurentiu** [comment]
Firma nu este prezenta pe targetare
