### ISSUE TITLE
Slb - "Listafirme.ro" instead of "Targetare.ro"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#587]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Slb" Company
3. Check the "Targetare.ro" button

EXPECTED RESULTS:
The button "Targetare.ro" is displayed

ACTUAL RESULTS:
"Listafirme.ro" instead of "Targetare.ro" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/760bb0fd-11eb-4fb7-ae9f-b7ae394cddd1)

**Comment by lalalaurentiu** [comment]
Fixed
