### ISSUE TITLE
DUAL IT - Careers link not working

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#594]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/dualit/index.html)
Hover over the company's logo.
Click on "Dual IT Careers".

EXPECTED RESULTS:
The careers section from the company's official website opens in new tab.

ACTUAL RESULTS:
A new tab opens, but it shows a 404 error.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/89eb5462-dd76-4bd7-aa0f-02d0de65577f)

**Comment by Sarra113** [comment]
The issue is still there: 


https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/3d2777a4-f2a9-4657-b7b0-dae3cf59ff51

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
Retested ✅
