### ISSUE TITLE
CBS - Logo of the company is missing 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers-UI#600]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL in browser
2.Type "CBS" in the search bar
3.Check if the logo of the company is displayed

EXPECTED RESULTS:
The logo must be displayed in the middle of the screen.

ACTUAL RESULTS:
There is no logo displayed.

<img width="1006" alt="cbs logo bug" src="https://github.com/peviitor-ro/Scrapers-UI/assets/129604131/5db3d808-d8d2-4614-833c-0e598efbc9ea">

**Comment by davidmondoc** [comment]
please retest after website update
