### ISSUE TITLE
Humanrise -  Database error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#605]
ENVIROMENT: production
COMPANY: Humanrise
URL: [Humanrise peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Click on Firme from footer.
Enter Humanrise in the search bar.
Click the button under the company's logo.
Click the Run Scraper button.

Expected result:
The the company's database is updated.

Actual result:
TypeError: Failed to fetch.

<img width="1639" alt="Screenshot at Feb 01 13-39-36" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/695b4ba6-bbcd-48a7-a83f-b85ef3382c9a">

**Comment by lalalaurentiu** [comment]
Fixed
