### ISSUE TITLE
BRAS - Missing company logo | Missing "Targetare" link | Careers link not working

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#606]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the [url](https://scrapers.peviitor.ro/src/bras/index.html) in browser.
Hover over the company's logo.

Click on the "Targetare" button.
Click on "Bras Careers"

EXPECTED RESULTS:

The company logo is visible in the square in the middle of the page.
There is a functioning 'Targetare' button (with link) just under the 'Careers' one. Link: https://targetare.ro/3634720/bras-srl
You are redirected to the careers section on the company's official website. Link: https://bras.ro/cariere-bras/#!#1

ACTUAL RESULTS:

The company logo is missing.
There is no 'Targetare' button.
The same url - https://scrapers.peviitor.ro/src/bras/index.html - opens in new tab.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/aad3c125-c4d2-45fa-a559-02dabd7ee1d0)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/e21c61e6-8b34-48ba-a041-1bc17d41185f)

https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/f49ca0cd-7b26-45ae-9723-c877d22ef491

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
Retested ✅
