### ISSUE TITLE
TMAX -  logo hard to see on the light background

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/Scrapers-UI#607]
ENVIROMENT: production
COMPANY: Tmax
URL: https://scrapers.peviitor.ro/src/tmax/index.html#
Browser: Google Chrome
Device: PC
OS: Windows10

Precondition:
The site https://scrapers.peviitor.ro/ must be open with google chrome .
Typing TMAX in the search bar.

Steps:

Open https://scrapers.peviitor.ro/
Enter Tmax in the search bar. Enter
Click the link with the name of the company.
Open the page with TMAX
Verify the box where the logo is displayed.

**Expected result:**
On https://scrapers.peviitor.ro/src/tmax/index.html# we can see the logo of the company well displayed.

**Actual result:**
Logo is hard to see because the text of the logo is white and the background has a light background
<img width="436" alt="TMAX - logo" src="https://github.com/peviitor-ro/Scrapers-UI/assets/129604131/94cf0e7a-ca84-4e10-adec-8cc372606297">

**Comment by davidmondoc** [comment]
please retest after website update

**Comment by DeedeeDL** [comment]
Retested.Fixed
