### ISSUE TITLE
EXPERTOGS - Company logo is missing

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#610]
ENVIROMENT: production
COMPANY: EXPERTOGS
URL: [EXPERTOGS firme.peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:

Click on Firme from footer.
Enter EXPERTOGS in the search bar.
Click the button under the company's logo.

Expected result:
You can see the company's logo.

Actual result:
The company logo is missing.

<img width="181" alt="Screenshot at Feb 05 16-31-35" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/1d74d538-ff60-4ba4-b007-c3298165c3e9">

**Comment by lalalaurentiu** [comment]
@AdelinaGuliman the company no longer exists so I deleted it
