### ISSUE TITLE
Flex - Missing Targetare Button (CHECKED!!)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#611]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Flex" Company
3. Check the "Targetare.ro" button

EXPECTED RESULTS:
The button "Targetare.ro" is displayed

ACTUAL RESULTS:
The "Targetare" button is missing.
On Targetare.ro the Flex company can be found by name "FLEXTRONICS ROMANIA SRL"

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/e4d6f9cd-c6b6-4324-95c2-b0e3ea65bd8a)

https://targetare.ro/10608391/flextronics-romania-srl

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/c7df50f9-5165-4519-9b06-8d9ca49f1b78)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/9a74d409-d8b7-4371-92d9-8d318dbf3c60)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/ee5ad324-16de-490a-ac17-cce10a615491)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by AdrianaCionca** [comment]
After retesting, the button "Targetare.ro" is displayed

![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/51ec8de3-5e95-4775-870b-a86e856b3d1b)
