### ISSUE TITLE
Bakertilly - Missing Targetare link

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/Scrapers-UI#615]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/bakertilly/index.html)
Hover over the company's logo.

EXPECTED RESULTS:
There is a 'Targetare' button (with link) just under the 'Careers' one. Link: https://targetare.ro/35412985/baker-tilly-corporate-management-services-srl

ACTUAL RESULTS:
The 'Targetare' button is missing.

Attachments:
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/136991701/36bff8f2-4399-44b7-9d6c-8d3ff6fcd7b9)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Sarra113** [comment]
Retested ✅
