### ISSUE TITLE
Rian-partners - Status INACTIV

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#631]
ENVIROMENT: production
COMPANY: Rian-partners
URL: [Rian-partners peviitor.ro](https://scrapers.peviitor.ro/src/rian-partners/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/rian-partners/index.html) must be open in browser.

Steps:
1. Click the Run Scraper button.

Expected result:
The the company's database is updated.

Actual result:
Status INACTIV
**"no-data 
No data in Local Storage
python3: can't open file 'rian-partners.py': [Errno 2] No such file or directory"**
<img width="969" alt="Screenshot at Feb 16 16-17-33" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/84e0c0d0-36b3-44ba-b10e-267644bb402f">

**Comment by lalalaurentiu** [comment]
Fixed
