### ISSUE TITLE
Antal - Database error

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers-UI#650]
ENVIROMENT: production
COMPANY: Antal
URL: [Antal scrapers.peviitor.ro](https://scrapers.peviitor.ro/src/antal/index.html)
Browser: Google Chrome
Device: Samsung Galaxy S8+
OS: Android

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
Enter Antal in the search bar.
Click the button under the company logo.
Click the Run Scraper button.

Expected result:
The the company's database is updated.

Actual result:
TypeError: Failed to fetch.

<img width="343" alt="Screenshot at Feb 20 18-16-22" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/a38c8920-64dc-48b3-bfb8-0ade7c3d3144">

**Comment by cristiol** [comment]
seems okay right now
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/142798921/43a961bc-7f74-4c22-85b2-69ad5e0f097a)
