### ISSUE TITLE
 Scraper-UI - Last Update

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/Scrapers-UI#66]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for any company between any hour from one minute up to 9 minutes
3. Check the writing of the minutes

EXPECTED RESULTS:
If the number of minutes is between 1 and 9, then in front of the number there is a space, space for the number of tens of minutes

ACTUAL RESULTS:
There is no space for the number of tens of minutes and the number of units of minutes is right next to the 2 dots

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/122023703/1895d89f-a6bb-41e9-a6c8-325bd07457aa)

**Comment by OvidiuAl3x** [comment]
Add 0 if is between 1 and 9
