### ISSUE TITLE
500 Internal Server Error on VALIDATOR when no logo is defined for the company

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/Scrapers-UI#670]
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/41440889/71e39cfb-b1e3-404d-adfe-e5497a87c22f)

Company: Alexandra
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/41440889/9a2ab632-d6d5-4c14-927a-00bcd7ccbfaf)

**Comment by lalalaurentiu** [comment]
Fixed
