### ISSUE TITLE
JW-Marriott - The link to Marriott's careers page is incorrect

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/Scrapers-UI#73]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/marriott/index.html
Browser: Chrome
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL in browser
  2.  Click button "Marriott Careers"
  3.  See that the link is to the ejobs page: https://www.ejobs.ro/company/marriott/3431
  4.  Open the correct page at https://jobs.marriott.com/marriott/jobs?lang=en-US&utm_medium=jobboard&utm_source=MarriottCareersWebsite&location=Romania&woe=12&stretchUnit=MILES&stretch=10&page=1
EXPECTED RESULTS:
The "Marriott Careers" button should open the Marriott careers page -> https://jobs.marriott.com/marriott/jobs?lang=en-US&utm_medium=jobboard&utm_source=MarriottCareersWebsite&location=Romania&woe=12&stretchUnit=MILES&stretch=10&page=1

ACTUAL RESULTS:
The "Marriott Careers" button opens the ejobs careers page ->  https://www.ejobs.ro/company/marriott/3431
![Screenshot 2023-10-06 215510_pagina ejobs](https://github.com/peviitor-ro/scrapers.js/assets/118441061/ffab6756-a3a5-4684-a089-a6dfa8dfb89b)
![Screenshot 2023-10-06 221133_pagina marriott careers](https://github.com/peviitor-ro/scrapers.js/assets/118441061/e475cdb2-fc36-4783-aa1b-cc72b8750ac0)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Link corect!
